//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STOCKTRACKING.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT
    {
        public int ACTID { get; set; }
        public string ACTNO { get; set; }
        public string ACTNAME { get; set; }
        public string TAXNO { get; set; }
        public string TAXOFFİCE { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string TOWN { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public string REGİON { get; set; }
        public string POSTALCODE { get; set; }
        public Nullable<int> PHONE1 { get; set; }
        public Nullable<int> PHONE2 { get; set; }
        public Nullable<int> GSM { get; set; }
        public string FAX { get; set; }
        public string WEBADDRESS { get; set; }
        public string EMAİL { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string DESCRİPTİON { get; set; }
    }
}
