//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STOCKTRACKING.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        public int STOCKID { get; set; }
        public string STOCKNAME { get; set; }
        public string STOCKNO { get; set; }
        public Nullable<decimal> PURCHASEPRİCE { get; set; }
        public Nullable<decimal> SALEPRİCE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string DESCRİPTİON { get; set; }
    }
}
